#include "sys_param.h"
#include "common_list.h"
#include "multirotor_geometry_param.h"

sys_param_data multirotor_geometry_param_list[MR_GEO_PARAM_LIST_SIZE];

void init_multirotor_geometry_param_list(void)
{
	init_sys_param_list(multirotor_geometry_param_list, MR_GEO_PARAM_LIST_SIZE);

	init_common_params();

	INIT_SYS_PARAM_FLOAT(MR_GEO_GAIN_ROLL_P, 2.95f);
	INIT_SYS_PARAM_FLOAT(MR_GEO_GAIN_ROLL_D, 0.36f);
	INIT_SYS_PARAM_FLOAT(MR_GEO_GAIN_PITCH_P, 2.95f);
	INIT_SYS_PARAM_FLOAT(MR_GEO_GAIN_PITCH_D, 0.36f);
	INIT_SYS_PARAM_FLOAT(MR_GEO_GAIN_YAW_P, 28.4f);
	INIT_SYS_PARAM_FLOAT(MR_GEO_GAIN_YAW_D, 1.96f);
	INIT_SYS_PARAM_FLOAT(MR_GEO_GAIN_RATE_YAW, 26.9f);
	INIT_SYS_PARAM_FLOAT(MR_GEO_GAIN_POS_X, 9.31f);
	INIT_SYS_PARAM_FLOAT(MR_GEO_GAIN_VEL_X, 6.86f);
	INIT_SYS_PARAM_FLOAT(MR_GEO_GAIN_POS_Y, 11.27f);
	INIT_SYS_PARAM_FLOAT(MR_GEO_GAIN_VEL_Y, 7.84f);
	INIT_SYS_PARAM_FLOAT(MR_GEO_GAIN_POS_Z, 8.53f);
	INIT_SYS_PARAM_FLOAT(MR_GEO_GAIN_VEL_Z, 3.92f);
	INIT_SYS_PARAM_FLOAT(MR_GEO_GAIN_POS_X_I, 0.0f);
	INIT_SYS_PARAM_FLOAT(MR_GEO_GAIN_POS_Y_I, 0.0f);
	INIT_SYS_PARAM_FLOAT(MR_GEO_GAIN_POS_Z_I, 0.0f);
	INIT_SYS_PARAM_FLOAT(MR_GEO_UAV_MASS, 1.15f);
	INIT_SYS_PARAM_FLOAT(MR_GEO_INERTIA_JXX, 0.01466f);
	INIT_SYS_PARAM_FLOAT(MR_GEO_INERTIA_JYY, 0.01466f);
	INIT_SYS_PARAM_FLOAT(MR_GEO_INERTIA_JZZ, 0.02848f);
	INIT_SYS_PARAM_FLOAT(PWM_TO_THRUST_C1, -2842.8f);
	INIT_SYS_PARAM_FLOAT(PWM_TO_THRUST_C2, 3951.7f);
	INIT_SYS_PARAM_FLOAT(PWM_TO_THRUST_C3, -1925.4f);
	INIT_SYS_PARAM_FLOAT(PWM_TO_THRUST_C4, 1381.3f);
	INIT_SYS_PARAM_FLOAT(PWM_TO_THRUST_C5, 257.37f);
	INIT_SYS_PARAM_FLOAT(PWM_TO_THRUST_C6, -7.0118f);
	INIT_SYS_PARAM_FLOAT(THRUST_TO_PWM_C1, 1.169e-14);
	INIT_SYS_PARAM_FLOAT(THRUST_TO_PWM_C2, -2.264e-11);
	INIT_SYS_PARAM_FLOAT(THRUST_TO_PWM_C3, 1.697e-08);
	INIT_SYS_PARAM_FLOAT(THRUST_TO_PWM_C4, -6.715e-06);
	INIT_SYS_PARAM_FLOAT(THRUST_TO_PWM_C5, 2.336e-03);
	INIT_SYS_PARAM_FLOAT(THRUST_TO_PWM_C6, 3.082e-02);
	INIT_SYS_PARAM_FLOAT(THRUST_MAX, 845.0f);

	load_param_list_from_flash();
}
