#include "sys_param.h"
#include "common_list.h"
#include "multirotor_geometry_param.h"

sys_param_data multirotor_geometry_param_list[MR_GEO_PARAM_LIST_SIZE];

void init_multirotor_geometry_param_list(void)
{
	init_sys_param_list(multirotor_geometry_param_list, MR_GEO_PARAM_LIST_SIZE);

	init_common_params();

	INIT_SYS_PARAM_FLOAT(MR_GEO_GAIN_ROLL_P, 2.95f);
	INIT_SYS_PARAM_FLOAT(MR_GEO_GAIN_ROLL_D, 0.36f);
	INIT_SYS_PARAM_FLOAT(MR_GEO_GAIN_PITCH_P, 2.95f);
	INIT_SYS_PARAM_FLOAT(MR_GEO_GAIN_PITCH_D, 0.36f);
	INIT_SYS_PARAM_FLOAT(MR_GEO_GAIN_YAW_P, 28.4f);
	INIT_SYS_PARAM_FLOAT(MR_GEO_GAIN_YAW_D, 1.96f);
	INIT_SYS_PARAM_FLOAT(MR_GEO_GAIN_RATE_YAW, 26.9f);
	INIT_SYS_PARAM_FLOAT(MR_GEO_GAIN_POS_X, 9.31f);
	INIT_SYS_PARAM_FLOAT(MR_GEO_GAIN_VEL_X, 6.86f);
	INIT_SYS_PARAM_FLOAT(MR_GEO_GAIN_POS_Y, 11.27f);
	INIT_SYS_PARAM_FLOAT(MR_GEO_GAIN_VEL_Y, 7.84f);
	INIT_SYS_PARAM_FLOAT(MR_GEO_GAIN_POS_Z, 8.53f);
	INIT_SYS_PARAM_FLOAT(MR_GEO_GAIN_VEL_Z, 3.92f);
	INIT_SYS_PARAM_FLOAT(MR_GEO_GAIN_POS_X_I, 0.0f);
	INIT_SYS_PARAM_FLOAT(MR_GEO_GAIN_POS_Y_I, 0.0f);
	INIT_SYS_PARAM_FLOAT(MR_GEO_GAIN_POS_Z_I, 0.0f);
	INIT_SYS_PARAM_FLOAT(MR_GEO_UAV_MASS, 1.15f);
	INIT_SYS_PARAM_FLOAT(MR_GEO_INERTIA_JXX, 0.01466f);
	INIT_SYS_PARAM_FLOAT(MR_GEO_INERTIA_JYY, 0.01466f);
	INIT_SYS_PARAM_FLOAT(MR_GEO_INERTIA_JZZ, 0.02848f);

	load_param_list_from_flash();
}
