#include "sys_param.h"
#include "common_list.h"
#include "multirotor_pid_param.h"

sys_param_data multirotor_pid_param_list[MR_PID_PARAM_LIST_SIZE];

void init_multirotor_pid_param_list(void)
{
	init_sys_param_list(multirotor_pid_param_list, MR_PID_PARAM_LIST_SIZE);

	init_common_params();

	INIT_SYS_PARAM_FLOAT(MR_PID_GAIN_ROLL_P, 0.41f);
	INIT_SYS_PARAM_FLOAT(MR_PID_GAIN_ROLL_D, 0.05f);
	INIT_SYS_PARAM_FLOAT(MR_PID_GAIN_PITCH_P, 0.41f);
	INIT_SYS_PARAM_FLOAT(MR_PID_GAIN_PITCH_D, 0.05f);
	INIT_SYS_PARAM_FLOAT(MR_PID_GAIN_YAW_P, 0.3f);
	INIT_SYS_PARAM_FLOAT(MR_PID_GAIN_YAW_D, 0.15f);
	INIT_SYS_PARAM_FLOAT(MR_PID_GAIN_RATE_YAW, 0.3f);
	INIT_SYS_PARAM_FLOAT(MR_PID_GAIN_POS_X_P, 15.0f);
	INIT_SYS_PARAM_FLOAT(MR_PID_GAIN_POS_X_I, 0.0f);
	INIT_SYS_PARAM_FLOAT(MR_PID_GAIN_POS_X_D, 13.0f);
	INIT_SYS_PARAM_FLOAT(MR_PID_GAIN_POS_Y_P, 15.0f);
	INIT_SYS_PARAM_FLOAT(MR_PID_GAIN_POS_Y_I, 0.0f);
	INIT_SYS_PARAM_FLOAT(MR_PID_GAIN_POS_Y_D, 13.0f);
	INIT_SYS_PARAM_FLOAT(MR_PID_GAIN_POS_Z_P, 3.5f);
	INIT_SYS_PARAM_FLOAT(MR_PID_GAIN_POS_Z_I, 0.0f);
	INIT_SYS_PARAM_FLOAT(MR_PID_GAIN_VEL_Z_P, 10.0f);
	INIT_SYS_PARAM_FLOAT(MR_PID_HEIGHT_FEEDFOWARD_PWM, 45.0f);

	load_param_list_from_flash();
}
