#ifndef __COMMON_LIST_H__
#define __COMMON_LIST_H__

enum {
	COMMON_RC_THROTTLE_MAX,
	COMMON_RC_THROTTLE_MIN,
	COMMON_RC_ROLL_MAX,
	COMMON_RC_ROLL_MIN,
	COMMON_RC_PITCH_MAX,
	COMMON_RC_PITCH_MIN,
	COMMON_RC_YAW_MAX,
	COMMON_RC_YAW_MIN,
	COMMON_RC_SAFETY_MAX,
	COMMON_RC_SAFETY_MIN,
	COMMON_RC_AUTO_FLIGHT_MAX,
	COMMON_RC_AUTO_FLIGHT_MIN,
	COMMON_RC_MODE_MAX,
	COMMON_RC_MODE_MID,
	COMMON_RC_MODE_MIN,
	/*----------------------*/
	COMMON_PARAM_CNT
} COMMON_PARAM_ID;

void init_common_params(void);

#endif
