#include "sys_param.h"

enum {
	MR_PID_GAIN_ROLL_P,
	MR_PID_GAIN_ROLL_D,

	MR_PID_GAIN_PITCH_P,
	MR_PID_GAIN_PITCH_D,

	MR_PID_GAIN_YAW_P,
	MR_PID_GAIN_YAW_D,

	MR_PID_GAIN_RATE_ONLY_YAW_D,

	MR_PID_GAIN_POS_X_P,
	MR_PID_GAIN_POS_X_I,
	MR_PID_GAIN_POS_X_D,

	MR_PID_GAIN_POS_Y_P,
	MR_PID_GAIN_POS_Y_I,
	MR_PID_GAIN_POS_Y_D,

	MR_PID_GAIN_POS_Z_P,
	MR_PID_GAIN_POS_Z_I,
	MR_PID_GAIN_POS_Z_D,
	MR_PID_HEIGHT_FEEDFOWARD_PWM
};

sys_param_data multirotor_pid_param_list[] = {
	SYS_PARAM_ATTR("GAIN_ROLL_P", MR_PID_GAIN_ROLL_P),
	SYS_PARAM_ATTR("GAIN_ROLL_D", MR_PID_GAIN_ROLL_D),

	SYS_PARAM_ATTR("GAIN_PITCH_P", MR_PID_GAIN_PITCH_P),
	SYS_PARAM_ATTR("GAIN_PITCH_D", MR_PID_GAIN_PITCH_D),

	SYS_PARAM_ATTR("GAIN_YAW_P", MR_PID_GAIN_YAW_P),
	SYS_PARAM_ATTR("GAIN_YAW_D", MR_PID_GAIN_YAW_D),

	SYS_PARAM_ATTR("GAIN_RATE_ONLY_YAW_D", MR_PID_GAIN_RATE_ONLY_YAW_D),

	SYS_PARAM_ATTR("GAIN_POS_X_P", MR_PID_GAIN_POS_X_P),
	SYS_PARAM_ATTR("GAIN_POS_X_I", MR_PID_GAIN_POS_X_I),
	SYS_PARAM_ATTR("GAIN_POS_X_D", MR_PID_GAIN_POS_X_D),

	SYS_PARAM_ATTR("GAIN_POS_Y_P", MR_PID_GAIN_POS_Y_P),
	SYS_PARAM_ATTR("GAIN_POS_Y_I", MR_PID_GAIN_POS_Y_I),
	SYS_PARAM_ATTR("GAIN_POS_Y_D", MR_PID_GAIN_POS_Y_D),

	SYS_PARAM_ATTR("GAIN_POS_Z_P", MR_PID_GAIN_POS_Z_P),
	SYS_PARAM_ATTR("GAIN_POS_Z_I", MR_PID_GAIN_POS_Z_I),
	SYS_PARAM_ATTR("GAIN_POS_Z_D", MR_PID_GAIN_POS_Z_D),
	SYS_PARAM_ATTR("HEIGHT_FEEDFOWARD_PWM", MR_PID_HEIGHT_FEEDFOWARD_PWM)
};

