#ifndef __PROJ_CONFIG_H__
#define __PROJ_CONFIG_H__

/* uav info */
#define UAV_ID 0

/* uav type */
#define UAV_TYPE_QUADROTOR 0
#define SELECT_UAV_TYPE UAV_TYPE_QUADROTOR

/* telemetry protocol */
#define TELEM_MAVLINK 0
#define TELEM_DEBUG_LINK 1
#define TELEM_SHELL 2
#define SELECT_TELEM TELEM_MAVLINK

/* ahrs algorithm */
#define AHRS_COMPLEMENTARY_FILTER 0
#define AHRS_MADGWICK_FILTER 1
#define SELECT_AHRS AHRS_MADGWICK_FILTER

/* quadrotor parameters */
#define QUADROTOR_USE_PID 0
#define QUADROTOR_USE_GEOMETRY 1
#define SELECT_CONTROLLER QUADROTOR_USE_GEOMETRY

/* heading sensor */
#define HEADING_SENSOR_USE_COMPASS 0
#define HEADING_SENSOR_USE_OPTITRACK 1
#define SELECT_HEADING_SENSOR HEADING_SENSOR_USE_OPTITRACK

/* height sensor */
#define HEIGHT_SENSOR_USE_BAROMETER 0
#define HEIGHT_SENSOR_USE_OPTITRACK 1
#define SELECT_HEIGHT_SENSOR HEIGHT_SENSOR_USE_OPTITRACK

/* position sensor */
#define POSITION_SENSOR_USE_GPS 0
#define POSITION_SENSOR_USE_OPTITRACK 1
#define SELECT_POSITION_SENSOR POSITION_SENSOR_USE_OPTITRACK

#endif
